import pandas as pd
scientific_to_common = {
    "Bucephala albeola": "Bufflehead",
    "Podilymbus podiceps": "Pied-billed Grebe",
    "Phalacrocorax auritus": "Double-crested Cormorant",
    "Haliaeetus leucocephalus": "Bald Eagle",
    "Colaptes auratus": "Northern Flicker",
    "Corvus brachyrhynchos": "American Crow",
    "Regulus calendula": "Ruby-crowned Kinglet",
    "Turdus migratorius": "American Robin",
    "Passerella iliaca": "Fox Sparrow",
    "Zonotrichia leucophrys": "White-crowned Sparrow",
    "Zonotrichia atricapilla": "Golden-crowned Sparrow",
    "Melospiza melodia": "Song Sparrow",
    "Pipilo maculatus": "Spotted Towhee",
    "Branta canadensis": "Canada Goose",
    "Megaceryle alcyon": "Belted Kingfisher",
    "Picoides pubescens": "Downy Woodpecker",
    "Picoides villosus": "Hairy Woodpecker",
    "Poecile atricapillus": "Black-capped Chickadee",
    "Regulus satrapa": "Golden-crowned Kinglet",
    "Haemorhous mexicanus": "House Finch",
    "Junco hyemalis": "Dark-eyed Junco",
    "Agelaius phoeniceus": "Red-winged Blackbird",
    "Setophaga coronata": "Yellow-rumped Warbler",
    "Mergus merganser": "Common Merganser",
    "Ardea herodias": "Great Blue Heron",
    "Poecile rufescens": "Chestnut-backed Chickadee",
    "Sitta canadensis": "Red-breasted Nuthatch",
    "Certhia americana": "Brown Creeper",
    "Thryomanes bewickii": "Bewick's Wren",
    "Mareca strepera": "Gadwall",
    "Mareca americana": "American Wigeon",
    "Anas platyrhynchos": "Mallard",
    "Calypte anna": "Anna's Hummingbird",
    "Larus brachyrhynchus": "Short-billed Gull",
    "Larus glaucescens": "Glaucous-winged Gull",
    "Buteo jamaicensis": "Red-tailed Hawk",
    "Dryocopus pileatus": "Pileated Woodpecker",
    "Lanius excubitor": "Northern Shrike",
    "Cyanocitta stelleri": "Steller's Jay",
    "Troglodytes pacificus": "Pacific Wren",
    "Cistothorus palustris": "Marsh Wren",
    "Sturnus vulgaris": "European Starling",
    "Columba livia domestica": "Rock Pigeon",
    "Psaltriparus minimus": "Bushtit",
    "Spinus pinus": "Pine Siskin",
    "Branta hutchinsii": "Cackling Goose",
    "Aythya valisineria": "Canvasback",
    "Aythya collaris": "Ring-necked Duck",
    "Bucephala clangula": "Common Goldeneye",
    "Lophodytes cucullatus": "Hooded Merganser",
    "Rallus limicola": "Virginia Rail",
    "Gallinago delicata": "Wilson's Snipe",
    "Podiceps auritus": "Horned Grebe",
    "Larus delawarensis": "Ring-billed Gull",
    "Tyto furcata": "Barn Owl",
    "Aphelocoma californica": "California Scrub-Jay",
    "Poecile gambeli": "Mountain Chickadee",
    "Aix sponsa": "Wood Duck",
    "Accipiter cooperii": "Cooper's Hawk",
    "Bombycilla cedrorum": "Cedar Waxwing",
    "Anas acuta": "Northern Pintail",
    "Anser albifrons": "Greater White-fronted Goose",
    "Anas crecca": "Green-winged Teal",
    "Aechmophorus occidentalis": "Western Grebe",
    "Anas clypeata": "Northern Shoveler",
    "Oxyura jamaicensis": "Ruddy Duck",
    "Spinus tristis": "American Goldfinch",
    "Fulica americana": "American Coot",
    "Gavia immer": "Common Loon",
    "Melospiza lincolnii": "Lincoln's Sparrow",
    "Bubo virginianus": "Great Horned Owl",
    "Haemorhous purpureus": "Purple Finch",
    "Leiothlypis celata": "Orange-crowned Warbler",
    "Nannopterum auritum": "Brown Pelican",
    "Ixoreus naevius": "Varied Thrush",
    "Strix varia": "Barred Owl",
    "Charadrius vociferus": "Killdeer",
    "Corvus corax": "Common Raven",
    "Tachycineta thalassina": "Violet-green Swallow",
    "Molothrus ater": "Brown-headed Cowbird",
    "Anthus rubescens": "American Pipit",
    "Calcarius lapponicus": "Lapland Longspur",
    "Pelecanus erythrorhynchos": "American White Pelican",
    "Larus heermanni": "Heermann's Gull",
    "Arenaria melanocephala": "Black Turnstone",
    "Calidris virgata": "Surfbird",
    "Mergus serrator": "Red-breasted Merganser",
    "Pandion haliaetus": "Osprey",
    "Botaurus lentiginosus": "American Bittern",
    "Streptopelia decaocto": "Eurasian Collared-Dove",
    "Larus smithsonianus": "American Herring Gull",
    "Hydroprogne caspia": "Caspian Tern",
    "Xanthocephalus xanthocephalus": "Yellow-headed Blackbird",
    "Piranga ludoviciana": "Western Tanager",
    "Aechmophorus clarkii": "Clark's Grebe",
    "Chroicocephalus philadelphia": "Bonaparte's Gull",
    "Melanitta perspicillata": "Surf Scoter",
    "Melanitta americana": "Black Scoter",
    "Aythya americana": "Redhead",
    "Aythya marila": "Greater Scaup",
    "Aythya affinis": "Lesser Scaup",
    "Mareca penelope": "Eurasian Wigeon",
    "Butorides virescens": "Green Heron",
    "Falco peregrinus": "Peregrine Falcon",
    "Coccothraustes vespertinus": "Evening Grosbeak",
    "Ardea alba": "Great Egret",
    "Anser caerulescens": "Snow Goose",
    "Sphyrapicus ruber": "Red-breasted Sapsucker",
    "Branta bernicla": "Brant",
    "Podiceps nigricollis": "Black-necked Grebe",
    "Larus glaucoides": "Iceland Gull",
    "Cygnus buccinator": "Trumpeter Swan",
    "Empidonax traillii": "Willow Flycatcher",
    "Selasphorus rufus": "Rufous Hummingbird",
    "Chaetura vauxi": "Vaux's Swift",
    "Spizella passerina": "Chipping Sparrow",
    "Icterus bullockii": "Bullock's Oriole",
    "Setophaga petechia": "Yellow Warbler",
    "Oreoscoptes montanus": "Sage Thrasher",
    "Lanius borealis": "Northern Shrike",
    "Dryobates villosus": "Hairy Woodpecker",
    "Accipiter striatus": "Sharp-shinned Hawk",
    "Astur cooperii": "Cooper's Hawk",
    "Zonotrichia albicollis": "White-throated Sparrow",
    "Anas platyrhynchos domesticus": "Domestic Mallard",
    "Corthylio calendula": "Ruby-crowned Kinglet",
    "Sturnella neglecta": "Western Meadowlark",
    "Megascops kennicottii": "Western Screech Owl",
    # Adding missing species
    "Contopus sordidulus": "Western Wood-Pewee",
    "Tachycineta bicolor": "Tree Swallow",
    "Tyrannus verticalis": "Western Kingbird",
    "Stelgidopteryx serripennis": "Northern Rough-winged Swallow",
    "Progne subis": "Purple Martin",
    "Parkesia noveboracensis": "Northern Waterthrush",
    "Spizelloides arborea": "American Tree Sparrow",
    "Porzana carolina": "Sora",
    "Geothlypis trichas": "Common Yellowthroat",
    "Setophaga townsendi": "Townsend's Warbler",
    "Falco columbarius": "Merlin",
    "Patagioenas fasciata": "Band-tailed Pigeon",
    "Cypseloides niger": "Black Swift",
    "Passerina amoena": "Lazuli Bunting",
    "Pheucticus melanocephalus": "Black-headed Grosbeak",
    "Phasianus colchicus": "Ring-necked Pheasant",
    "Carduelis psaltria": "Lesser Goldfinch",
    "Passerculus sandwichensis": "Savannah Sparrow",
    "Empidonax difficilis": "Pacific-slope Flycatcher",
    "Cepphus columba": "Pigeon Guillemot",
    "Phalacrocorax pelagicus": "Pelagic Cormorant",
    "Larus occidentalis": "Western Gull",
    "Numenius phaeopus": "Whimbrel",
    "Catharus guttatus": "Hermit Thrush",
    "Catharus ustulatus": "Swainson's Thrush",
    "Vireo huttoni": "Hutton's Vireo",
    "Spatula cyanoptera": "Cinnamon Teal",
    "Pheucticus ludovicianus": "Rose-breasted Grosbeak",
    "Vireo gilvus": "Warbling Vireo",
    "Zenaida macroura": "Mourning Dove",
    "Falco sparverius": "American Kestrel",
    "Icteria virens": "Yellow-breasted Chat",
    "Meleagris gallopavo domesticus": "Domestic Turkey",
    "Actitis macularius": "Spotted Sandpiper",
    "Lanius ludovicianus": "Loggerhead Shrike",
    "Sialia mexicana": "Western Bluebird",
    "Sayornis saya": "Say's Phoebe",
    "Sialia currucoides": "Mountain Bluebird",
}

# Load CSV into pandas DataFrame
file = 'English_species_file_L351484.csv'  # Replace with your CSV file path
df = pd.read_csv(file)

# Check if 'Species' column exists
if 'Species' in df.columns:
    # Replace scientific names with common names
    df['Species'] = df['Species'].map(scientific_to_common).fillna(df['Species'])
else:
    print("Warning: 'Species' column not found in the CSV file")

# Save the updated DataFrame to a new CSV
output_file = 'English_common_species_file_L351484.csv'
df.to_csv(output_file, index=False)
print(f"Updated file saved as {output_file}")