import pandas as pd
scientific_to_common = {
    'Regulus satrapa': "Golden-crowned Kinglet",
    'Strix varia': "Barred Owl",
    'Sphyrapicus': "Red-breasted Sapsucker",
    'Certhia americana': "Brown Creeper",
    'Thryomanes bewickii': "Bewick's Wren",
    'Troglodytes pacificus': "Pacific Wren",
    'Astur cooperii': "Cooper's Hawk",
    'Haemorhous mexicanus': "House Finch",
    'Turdus migratorius': "American Robin",
    'Haliaeetus leucocephalus': "Bald Eagle",
    'Dryocopus pileatus': "Pileated Woodpecker",
    'Larus glaucescens × occidentalis': "Western x Glaucous-winged Gull (hybrid)",
    'Urile pelagicus': "Pelagic Cormorant",
    'Podiceps grisegena': "Horned Grebe",
    'Setophaga townsendi': "Townsend's Warbler",
    'Corthylio calendula': "Ruby-crowned Kinglet",
    'Spinus pinus': "Pine Siskin",
    'Mergus serrator': "Red-breasted Merganser",
    'Podiceps auritus': "Red-necked Grebe",
    'Bucephala albeola': "Bufflehead",
    'Bucephala clangula': "Common Goldeneye",
    'Nannopterum auritum': "Brandt's Cormorant",
    'Larus brachyrhynchus': "Western Gull",
    'Mareca americana': "American Wigeon",
    'Larus smithsonianus': "American Herring Gull",
    'Gavia stellata': "Red-throated Loon",
    'Dryobates villosus': "Downy Woodpecker",
    'Sitta canadensis': "Red-breasted Nuthatch",
    'Setophaga coronata coronata': "Yellow-rumped Warbler",
    'Colaptes auratus luteus × cafer': "Northern Flicker (hybrid)",
    'Chroicocephalus philadelphia': "Bonaparte's Gull",
    'Junco hyemalis': "Dark-eyed Junco",
    'Zonotrichia atricapilla': "White-crowned Sparrow",
    'Larinae': "Gulls",
    'Anatidae': "Ducks and Geese",
    'Aegolius acadicus': "Northern Saw-whet Owl",
    'Passerella iliaca': "Fox Sparrow",
    'Plectrophenax nivalis': "Snow Bunting",
    'Zonotrichia leucophrys': "White-throated Sparrow",
    'Cyanocitta stelleri': "Steller's Jay",
    'Vireo huttoni': "Hutton's Vireo",
    'Colaptes auratus': "Northern Flicker",
    'Pipilo maculatus': "Spotted Towhee",
    'Anas platyrhynchos': "Mallard",
    'Megaceryle alcyon': "Belted Kingfisher",
    'Anas platyrhynchos platyrhynchos': "Mallard (Eastern)",
    'Columba livia domestica': "Rock Pigeon",
    'Sturnus vulgaris': "European Starling",
    'Pandion haliaetus': "Osprey",
    'Melospiza melodia': "Song Sparrow",
    'Ardea herodias': "Great Blue Heron",
    'Anseriformes': "Waterfowl",
    'Molothrus ater': "Brown-headed Cowbird",
    'Falco columbarius': "Merlin",
    'Leiothlypis celata': "Orange-crowned Warbler",
    'Sphyrapicus ruber': "Red-naped Sapsucker",
    'Poecile rufescens': "Chestnut-backed Chickadee",
    'Calidris mauri': "Western Sandpiper",
    'Butorides virescens': "Green Heron",
    'Falco peregrinus': "Peregrine Falcon",
    'Larus glaucescens': "Glaucous-winged Gull",
    'Corvus brachyrhynos': "American Crow",
    'Psaltriparus minimus': "Bushtit",
    'Larus delawarensis': "Ring-billed Gull",
    'Poecile atricapillus': "Black-capped Chickadee",
    'Calidris alba': "Sanderling",
    'Charadrius semipalmatus': "Semipalmated Plover",
    'Vireo gilvus': "Warbling Vireo",
    'Calypte anna': "Anna's Hummingbird",
    'Spinus tristis': "American Goldfinch",
    'Cardellina pusilla': "Wilson's Warbler",
    'Contopus sordidulus': "Western Wood-Pewee",
    'Calidris minutilla': "Least Sandpiper",
    'Contopus cooperi': "Olive-sided Flycatcher",
    'Actitis macularius': "Spotted Sandpiper",
    'Laridae': "Family of Seabirds",
    'Hydroprogne caspia': "Caspian Tern",
    'Cepphus columba': "Pigeon Guillemot",
    'Hirundo rustica': "Barn Swallow",
    'Bombycilla cedrorum': "Cedar Waxwing",
    'Buteo jamaicensis': "Red-tailed Hawk",
    'Passer domesticus': "House Sparrow",
    'Larus californicus': "California Gull",
    'Passerculus sandwichensis': "Savannah Sparrow",
    'Branta canadensis': "Canada Goose",
    'Tachycineta thalassina': "Tree Swallow",
    'Selasphorus rufus': "Rufous Hummingbird",
    'Haemorhous purpureus': "Purple Finch",
    'Empidonax difficilis': "Pacific-slope Flycatcher",
    'Pinicola enucleator': "Pine Grosbeak",
    'Charadrius vociferus': "Killdeer",
    'Euphagus carolinus': "Rusty Blackbird",
    'Tyrannus tyrannus': "Eastern Kingbird",
    'Catharus ustulatus': "Swainson's Thrush",
    'Aves': "Birds",
    'Patagioenas fasciata': "Band-tailed Pigeon",
    'Anas crecca': "Green-winged Teal",
    'Mareca strepera': "Gadwall",
    'Aythya americana': "Redhead",
    'Spatula clypeata': "Northern Shoveler",
    'Lophodytes cucullatus': "Hooded Merganser",
    'Pelecanus occidentalis': "Brown Pelican",
    'Larus fuscus': "Lesser Black-backed Gull",
    'Ixoreus naevius': "Varied Thrush",
    'Leiothlypis': "Vireos",
    'Dryobates pubescens': "Downy Woodpecker",
    'Accipitridae': "Hawks, Eagles, and Kites",
    'Melanitta perspicillata': "Surf Scoter",
    'Callipepla californica': "California Quail",
    'Stercorarius parasiticus': "Parasitic Jaeger",
    'Setophaga nigrescens': "Black-throated Gray Warbler",
    'Setophaga coronata': "Yellow-rumped Warbler",
    'Melanitta americana': "American Scoter",
    'Mergus merganser': "Common Merganser",
    'Bucephala islandica': "Barrow's Goldeneye",
    'Aythya marila': "Greater Scaup",
    'Aythya affinis': "Lesser Scaup",
    'Podilymbus podiceps': "Pied-billed Grebe",
    'Melospiza lincolnii': "Lincoln's Sparrow",
    'Aechmophorus occidentalis': "Western Grebe",
    'Mniotilta varia': "Black-and-white Warbler",
    'Histrionicus histrionicus': "Harlequin Duck",
    'Phalaenoptilus nuttallii': "Nuttall's Cottontail",
    'Larus occidentalis': "Western Gull",
    'Numenius phaeopus': "Whimbrel",
    'Dryobates': "Woodpeckers",
    'Ardea herodias fannini': "Great Blue Heron (Fannini subspecies)",
    'Leiothlypis celata lutescens': "Orange-crowned Warbler (Lutescens subspecies)",
    'Haemorhous': "Finches",
    'Charadriidae': "Plovers",
    'Passeriformes': "Perching Birds",
    'Empidonax traillii': "Willow Flycatcher",
    'Bubo virginianus': "Great Horned Owl",
    'Pheucticus melanocephalus': "Black-headed Grosbeak",
    'Sturnella neglecta': "Western Meadowlark",
    'Empidonax hammondii': "Hammond's Flycatcher",
    'Sialia currucoides': "Mountain Bluebird",
    'Branta bernicla': "Brant Goose",
    'Cerorhinca monocerata': "Rhinoceros Auklet",
    'Mareca penelope': "Eurasian Wigeon",
    'Corvus corax': "Common Raven"
}
# Load CSV into pandas DataFrame
file = 'filtered_L128530_bird_data.csv'  # Replace with your CSV file path
df = pd.read_csv(file)

# Check if 'Species' column exists
if 'Species' in df.columns:
    # Replace scientific names with common names
    df['Species'] = df['Species'].map(scientific_to_common).fillna(df['Species'])
else:
    print("Warning: 'Species' column not found in the CSV file")

# Save the updated DataFrame to a new CSV
output_file = 'updated_species_file.csv'
df.to_csv(output_file, index=False)
print(f"Updated file saved as {output_file}")