import pandas as pd
scientific_to_common = {
    "Bufflehead": "Bucephala albeola",
    "Pied-billed Grebe": "Podilymbus podiceps",
    "Double-crested Cormorant": "Phalacrocorax auritus",
    "Bald Eagle": "Haliaeetus leucocephalus",
    "Northern Flicker": "Colaptes auratus",
    "American Crow": "Corvus brachyrhynchos",
    "Ruby-crowned Kinglet": "Regulus calendula",
    "American Robin": "Turdus migratorius",
    "Fox Sparrow": "Passerella iliaca",
    "White-crowned Sparrow": "Zonotrichia leucophrys",
    "Golden-crowned Sparrow": "Zonotrichia atricapilla",
    "Song Sparrow": "Melospiza melodia",
    "Spotted Towhee": "Pipilo maculatus",
    "Canada Goose": "Branta canadensis",
    "Belted Kingfisher": "Megaceryle alcyon",
    "Downy Woodpecker": "Picoides pubescens",
    "Hairy Woodpecker": "Picoides villosus",
    "Black-capped Chickadee": "Poecile atricapillus",
    "Golden-crowned Kinglet": "Regulus satrapa",
    "House Finch": "Haemorhous mexicanus",
    "Dark-eyed Junco": "Junco hyemalis",
    "Red-winged Blackbird": "Agelaius phoeniceus",
    "Yellow-rumped Warbler": "Setophaga coronata",
    "Common Merganser": "Mergus merganser",
    "Great Blue Heron": "Ardea herodias",
    "Chestnut-backed Chickadee": "Poecile rufescens",
    "Red-breasted Nuthatch": "Sitta canadensis",
    "Brown Creeper": "Certhia americana",
    "Bewick's Wren": "Thryomanes bewickii",
    "Gadwall": "Mareca strepera",
    "American Wigeon": "Mareca americana",
    "Mallard": "Anas platyrhynchos",
    "Anna's Hummingbird": "Calypte anna",
    "Short-billed Gull": "Larus brachyrhynchus",
    "Glaucous-winged Gull": "Larus glaucescens",
    "Red-tailed Hawk": "Buteo jamaicensis",
    "Pileated Woodpecker": "Dryocopus pileatus",
    "Northern Shrike": "Lanius excubitor",
    "Steller's Jay": "Cyanocitta stelleri",
    "Pacific Wren": "Troglodytes pacificus",
    "Marsh Wren": "Cistothorus palustris",
    "European Starling": "Sturnus vulgaris",
    "Rock Pigeon": "Columba livia domestica",
    "Bushtit": "Psaltriparus minimus",
    "Pine Siskin": "Spinus pinus",
    "Cackling Goose": "Branta hutchinsii",
    "Canvasback": "Aythya valisineria",
    "Ring-necked Duck": "Aythya collaris",
    "Common Goldeneye": "Bucephala clangula",
    "Hooded Merganser": "Lophodytes cucullatus",
    "Virginia Rail": "Rallus limicola",
    "Wilson's Snipe": "Gallinago delicata",
    "Horned Grebe": "Podiceps auritus",
    "Ring-billed Gull": "Larus delawarensis",
    "American Barn Owl": "Tyto furcata",
    "California Scrub-Jay": "Aphelocoma californica",
    "Mountain Chickadee": "Poecile gambeli",
    "Wood Duck": "Aix sponsa",
    "Cooper's Hawk": "Accipiter cooperii",
    "Cedar Waxwing": "Bombycilla cedrorum",
    "Northern Pintail": "Anas acuta",
    "Greater White-fronted Goose": "Anser albifrons",
    "Green-winged Teal": "Anas crecca",
    "Western Grebe": "Aechmophorus occidentalis",
    "Northern Shoveler": "Anas clypeata",
    "Ruddy Duck": "Oxyura jamaicensis",
    "American Goldfinch": "Spinus tristis",
    "American Coot": "Fulica americana",
    "Common Loon": "Gavia immer",
    "Lincoln's Sparrow": "Melospiza lincolnii",
    "Great Horned Owl": "Bubo virginianus",
    "Purple Finch": "Haemorhous purpureus",
    "Orange-crowned Warbler": "Leiothlypis celata",
    "Haemorhous mexicanus": "House Finch",
    "Megaceryle alcyon": "Belted Kingfisher",
    "Corvus brachyrhynchos": "American Crow",
    "Anas platyrhynchos": "Mallard",
    "Branta canadensis": "Canada Goose",
    "Cistothorus palustris": "Marsh Wren",
    "Zonotrichia atricapilla": "Golden-crowned Sparrow",
    "Buteo jamaicensis": "Red-tailed Hawk",
    "Turdus migratorius": "American Robin",
    "Haliaeetus leucocephalus": "Bald Eagle",
    "Selasphorus rufus": "Anna's Hummingbird",
    "Zonotrichia leucophrys": "White-crowned Sparrow",
    "Calypte anna": "Anna's Hummingbird",
    "Cyanocitta stelleri": "Steller's Jay",
    "Colaptes auratus": "Northern Flicker",
    "Columba livia domestica": "Rock Pigeon",
    "Catharus ustulatus": "Hermit Thrush",
    "Melospiza melodia": "Song Sparrow",
    "Passerculus sandwichensis": "Savannah Sparrow",
    "Poecile atricapillus": "Black-capped Chickadee",
    "Mareca strepera": "Gadwall",
    "Pandion haliaetus": "Osprey",
    "Larus glaucescens": "Glaucous-winged Gull",
    "Astur cooperii": "Cooper's Hawk",
    "Poecile rufescens": "Red-breasted Nuthatch",
    "Junco hyemalis": "Dark-eyed Junco",
    "Falco sparverius": "American Kestrel",
    "Aix sponsa": "Wood Duck",
    "Tyto furcata": "Barn Owl",
    "Ardea herodias": "Great Blue Heron",
    "Contopus sordidulus": "Western Wood-Pewee",
    "Tachycineta bicolor": "Tree Swallow",
    "Molothrus ater": "Brown-headed Cowbird",
    "Spinus tristis": "American Goldfinch",
    "Progne subis": "Purple Martin",
    "Catharus guttatus": "Wood Thrush",
    "Pipilo maculatus": "Spotted Towhee",
    "Icteria virens": "Yellow-breasted Chat",
    "Mergus merganser": "Common Merganser",
    "Pheucticus melanocephalus": "Black-headed Grosbeak",
    "Bombycilla cedrorum": "Cedar Waxwing",
    "Passerina amoena": "Lazuli Bunting",
    "Geothlypis trichas": "Common Yellowthroat",
    "Tyrannus verticalis": "Western Kingbird",
    "Cypseloides niger": "Black Swift",
    "Patagioenas fasciata": "Band-tailed Pigeon",
    "Agelaius phoeniceus": "Red-winged Blackbird",
    "Charadrius vociferus": "Killdeer",
    "Tachycineta thalassina": "Violet-green Swallow",
    "Stelgidopteryx serripennis": "Northern Rough-winged Swallow",
    "Anser albifrons": "Greater White-fronted Goose",
    "Meleagris gallopavo domesticus": "Domestic Turkey",
    "Setophaga coronata": "Yellow-rumped Warbler",
    "Gallinago delicata": "Wilson's Snipe",
    "Actitis macularius": "Spotted Sandpiper",
    "Lanius ludovicianus": "Loggerhead Shrike",
    "Aythya collaris": "Ring-necked Duck",
    "Sturnella neglecta": "Western Meadowlark",
    "Sialia mexicana": "Western Bluebird",
    "Regulus satrapa": "Golden-crowned Kinglet",
    "Phasianus colchicus": "Ring-necked Pheasant",
    "Psaltriparus minimus": "Bushtit",
    "Anas crecca": "Green-winged Teal",
    "Sayornis saya": "Say's Phoebe",
    "Sialia currucoides": "Mountain Bluebird",
    "Thryomanes bewickii": "Bewick's Wren",
    "Passerella iliaca": "Fox Sparrow",
    "Larus brachyrhynchus": "Short-billed Gull",
    "Sturnus vulgaris": "European Starling",
    "Fulica americana": "American Coot",
    "Megascops kennicottii": "Flammulated Owl",
    "Strix varia": "Barred Owl",
    "Lanius borealis": "Northern Shrike",
    "Branta hutchinsii": "Cackling Goose",
    "Haemorhous purpureus": "Purple Finch",
    "Larus delawarensis": "Ring-billed Gull",
    "Cygnus buccinator": "Trumpeter Swan",
    "Ixoreus naevius": "Varied Thrush",
    "Bucephala clangula": "Common Goldeneye",
    "Nannopterum auritum": "Brown Pelican",
    "Lophodytes cucullatus": "Hooded Merganser",
    "Sitta canadensis": "Mountain Chickadee",
    "Melospiza lincolnii": "Lincoln's Sparrow",
    "Corthylio calendula": "Hepatic Tanager",
    "Pheucticus ludovicianus": "Scarlet Tanager",
    "Falco columbarius": "Merlin",
    "Zonotrichia albicollis": "White-throated Sparrow",
    "Anas platyrhynchos domesticus": "Domestic Mallard",
    "Setophaga townsendi": "Townsend's Warbler",
    "Spizella passerina": "Chipping Sparrow",
    "Vireo gilvus": "Warbling Vireo",
    "Zenaida macroura": "Mourning Dove",
    "Empidonax traillii": "Willow Flycatcher",
    "Oreoscoptes montanus": "Sagebrush Sparrow",
    "Chaetura vauxi": "Vaux's Swift",
    "Icterus bullockii": "Bullock's Oriole",
    "Setophaga petechia": "Yellow Warbler",
    "Sphyrapicus ruber": "Red-breasted Sapsucker",
    "Dryobates villosus": "Hairy Woodpecker",
    "Accipiter striatus": "Sharp-shinned Hawk"
}

# Load CSV into pandas DataFrame
file = 'English_species_file_L351484.csv'  # Replace with your CSV file path
df = pd.read_csv(file)

# Check if 'Species' column exists
if 'Species' in df.columns:
    # Replace scientific names with common names
    df['Species'] = df['Species'].map(scientific_to_common).fillna(df['Species'])
else:
    print("Warning: 'Species' column not found in the CSV file")

# Save the updated DataFrame to a new CSV
output_file = 'English_common_species_file_L351484.csv'
df.to_csv(output_file, index=False)
print(f"Updated file saved as {output_file}")